name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}

    - name: get-date
      run: echo "DATE=$(date +"%F")" >> $GITHUB_ENV

    - name: prepare-upload
      run: |
        zip brainf-DEBUG_${{ env.DATE }}.zip brainf ../hello.b

    - name: upload
        uses: actions/upload-artifact@v2
        with:
          name: brainf-x64-DEBUG_${{ env.DATE }}
          path: build/brainf-DEBUG_${{ env.DATE }}
